language: python
python: 
 - "3.6"

dist: trusty
sudo: required

services:
 - mysql

addons:
  apt:
    packages:
    - python-dev 
    - build-essential 
    - graphviz 
    - python-pip 
    - python3-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev
    - docbook
    - python-apt
    - dblatex
    - texlive-latex-extra 
    - docbook-utils
    - libxml2-dev
    - libxslt1-dev

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=cairis_travis.cnf XML_CATALOG_FILES=$CAIRIS_SRC/config/catalog $CAIRIS_CFG_DIR=./travisConfig

install:
- pip3 install -r requirements.txt
- pip3 install -r test_requirements.txt
- pip3 install coveralls
- sudo pip3 install selenium

before_script:
- wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin

script: 
- py.test cairis/test --doctest-modules -v --cov cairis/core cairis/daemon cairis/controllers cairis/data cairis/tools --cov-report term-missing

after_success:
- coveralls
- codecov 
