language: python
python:
- "2.7"
- '3.6'
dist: trusty
sudo: required
services:
- mysql
addons:
  apt:
    packages:
    - python-dev
    - build-essential
    - graphviz
    - python-pip
    - python-numpy
    - git
    - python-mysqldb
    - libmysqlclient-dev
    - docbook
    - python-apt
    - dblatex
    - texlive-latex-extra
    - docbook-utils
    - libxml2-dev
    - libxslt1-dev
    - google-chrome-stable

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=cairis_travis.cnf XML_CATALOG_FILES=$CAIRIS_SRC/config/catalog
    $CAIRIS_CFG_DIR=./travisConfig

install:
- pip install -r test_requirements.txt
- pip install -r requirements.txt

before_script:
- latestChromeDriver=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
- wget https://chromedriver.storage.googleapis.com/$latestChromeDriver/chromedriver_linux64.zip
- sudo unzip chromedriver_linux64 -d /usr/bin
- sudo chmod a+x /usr/bin/chromedriver

script:
- behave
- py.test cairis/test --doctest-modules -v --cov cairis/core cairis/daemon cairis/controllers
  cairis/data cairis/tools --cov-report term-missing

after_success:
- coveralls
- codecov
