language: python
python:
- '3.6'
dist: xenial
sudo: required
services:
- mysql
addons:
  apt:
    packages:
    - python-dev
    - build-essential
    - graphviz
    - python3-pip
    - python3-numpy
    - git
    - libmysqlclient-dev
    - docbook
    - python3-apt
    - dblatex
    - texlive-latex-extra
    - docbook-utils
    - libxml2-dev
    - libxslt1-dev

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=cairis_travis.cnf XML_CATALOG_FILES=$CAIRIS_SRC/config/catalog
    $CAIRIS_CFG_DIR=./travisConfig

before_install: 
- sudo cp $CAIRIS_CFG_DIR/mysqld.cnf /etc/mysql/mysql.conf.d/
- sudo service mysql restart

install:
- pip install -r test_requirements.txt
- pip install -r requirements.txt

script:
- py.test cairis/test --doctest-modules -v --cov cairis/core cairis/daemon cairis/controllers
  cairis/data cairis/tools --cov-report term-missing

after_success:
- coveralls
- codecov
